### PR TITLE
Make a Hashable version of the Collection API

### PR DESCRIPTION
**Pull request by asayers**
### Summary

All existing modules preserve the same APIs, semantics, and performance characteristics (with the exception of `FRP.Euphoria.Collection`, which has mysteriously become a bit faster). In addition, we have the following new modules:

- `FRP.Euphoria.EnumCollection.Lazy`
- `FRP.Euphoria.EnumCollection.Strict`
- `FRP.Euphoria.HashCollection.Lazy`
- `FRP.Euphoria.HashCollection.Strict`

They all expose the same interface, but with different key constraints and strictness properties. The  `Collection` type exported by all modules is the same, and most of the code is shared (via `FRP.Euphoria.Internal.GenericCollection`).

Operationally, the functions in `Collection.Hashable` are slightly slower than those in `Collection.Enum`. See [here](http://www.asayers.org/euphoria-bench-6c3fceb.html) for benchmarks.

### Motivation

As of 0.6.0.1, many of the functions in `FRP.Euphoria.Collection` impose an `Enum` constraint on the `Collection`'s key type because internally they construct an `EnumMap`. Often, however, `Hashable` is the better constraint since instances can be painlessly derived using the `Generic` machinery. That said, it's desirable to keep the existing `Enum`-based versions of the functions for speed and API compatibility.

This MR generalises all functions over `Collection`s, such that they take an additional value of type `Maplike c k => Proxy (c k)` which determines what kind of container to use internally, and thus what kind of constraints are placed on the key type. These functions are exported by `FRP.Euphoria.Collection.Generic`, which is not intended to be used directly. Specialised interfaces are exposed by `FRP.Euphoria.Collection.Hashable` and `FRP.Euphoria.Collection.Enum`, providing the desired API and backward-compatible API respectively. Other map-like containers could be supported easily.

### CODE REVIEW

**Comment by maoe** [comment]
Comments from our internal chat:

* It's a bit weird that using the functions in Collection.Hashable will evaluate the elements, while the equivalent functions in Collection.Enum won't.
* Maybe we should measure the performance.

**Comment by asayers** [comment]
Also: include both APIs in the tests.

**Comment by asayers** [comment]
Some benchmark results:

- [`feat-hashable`](http://asayers.org/euphoria-bench-9741327.html) for comparing Collection.Enum and Collection.Hashable
- [`feat-benchmark`](http://www.asayers.org/euphoria-bench-fe1cae6.html) for comparison with the old code.

It looks like refactoring Collection into Collection.Enum made it faster, which is suspicious...

**Comment by asayers** [comment]
Now with more benchmarks: [`feat-hashable`](http://www.asayers.org/euphoria-bench-7dd3898.html)

**Comment by asayers** [comment]
Even more benchmarks: [`feat-hashable`](http://www.asayers.org/euphoria-bench-0da0e5a.html)

Collection.Enum and Collection.Hashable are substantially the same, with the exception of `collectionFromDiscreteList`, for which Collection.Enum is faster.

**Comment by maoe** [comment]
Any thoughts on the Lazy vs. Strict argument?

Maybe I should have point this out earlier, but I think it does make sense to add `Maplike` instances for all `Data.(Hash|Enum)?Map.(Strict|Lazy)` combinations, otherwise we can't do it without using orphan instances. Also the strictness properties should be documented in the module headers. Or even better, we could rename them to:

* FRP.Euphoria.Collection.EnumMap.Lazy
* FRP.Euphoria.Collection.HashMap.Strict

to avoid confusion.

**Comment by asayers** [comment]
Since we don't export `Maplike`, making orphans isn't possible. It might be worth exposing explicitly lazy/strict versions of the collection API though:

- `FRP.Euphoria.EnumCollection.Lazy`
- `FRP.Euphoria.EnumCollection.Strict`
- `FRP.Euphoria.HashCollection.Lazy`
- `FRP.Euphoria.HashCollection.Strict`

For this we'd need to `newtype` the `(Hash|Enum)?Map` types in order to add the necessary `Maplike` instances.

**Comment by maoe** [comment]
I see. Yes, we need to newtype `(Hash)?Map`s. We don't need for `EnumMap`s though as they are separate types.

**Comment by asayers** [comment]
http://www.asayers.org/euphoria-bench-6c3fceb.html

**Pull request merged**
