### PR TITLE
Add mapCollectionM

### PR DESCRIPTION
**Pull request by asayers**
```haskell
mapCollectionM
    :: (MonadSignalGen m, c k)
    => (a -> SignalGen b)
    -> Collection k a
    -> m (Collection k b)
```

### CODE REVIEW

**Comment by asayers** [comment]
Perhaps `mapCollectionSGen` would be better?

**Comment by takano-akio** [comment]
+1.

I like `mapCollectionM` better, because it tells me what kind of function it is.

**Comment by fumieval** [comment]
`traverseCollection` sound more with-it to me.

**Comment by fumieval** [comment]
I'd rather define `sequenceCollection = traverseCollection id`

**Comment by maoe** [comment]
LGTM

**Comment by asayers** [comment]
fumieval: do you have a reason for wanting `sequenceCollection = mapCollectionM id`?

**Comment by fumieval** [comment]
The `mapCollectionM` needs to traverse the collection twice. If we define `mapCollectionM` directly, it will be faster and we can change the implementation of  `sequenceCollection` to a trivial one.

**Pull request merged**
